spring:
  messages:
    encoding: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:./database/tool-masters-bot-db
  jpa:
    hibernate:
      ddl-auto: update

telegram:
  bot:
    token:
    allowedChatId:
    zonedId: