spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/bot-db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
telegram:
  bot:
    token: ${NEWS.CHECKER.BOT.TOKEN}